/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

public class Liburuak {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new Liburuak().getGreeting());
    }
}
